owner: konyogony
repo: status

sites:
  - name: Portfolio
    url: https://konyogony.dev

  - name: Physics Blog
    url: https://physics.konyogony.dev

  - name: Ocean
    url: https://ocean.konyogony.dev

  - name: Hypr Project
    url: https://hypr.konyogony.dev

  - name: Stats API
    url: https://api.konyogony.dev/get-stats
    method: GET
    expectedStatusCodes:
      - 200

  - name: Physics Blog Asset (WebP)
    url: https://physics.konyogony.dev/assets/two-plates.webp
    expectedStatusCodes:
      - 200

  - name: Zipline CDN (Ocean WebP)
    url: https://cdn.konyogony.dev/u/ocean-kony.webp
    expectedStatusCodes:
      - 200

  - name: Zipline CDN (Full Paper PDF)
    url: https://cdn.konyogony.dev/u/full.pdf
    expectedStatusCodes:
      - 200

  - name: Zipline CDN (Short Paper PDF)
    url: https://cdn.konyogony.dev/u/shortened.pdf
    expectedStatusCodes:
      - 200

  - name: "Redirect: Ocean Full Paper"
    url: https://ocean.konyogony.dev/full
    expectedStatusCodes:
      - 200
      - 301

  - name: "Redirect: Ocean Short Paper"
    url: https://ocean.konyogony.dev/short
    expectedStatusCodes:
      - 200
      - 301

  - name: "Redirect: Steam"
    url: https://konyogony.dev/s/steam
    expectedStatusCodes:
      - 200
      - 308

  - name: "Redirect: Spotify"
    url: https://konyogony.dev/s/spotify
    expectedStatusCodes:
      - 200
      - 308

  - name: "Redirect: Discord"
    url: https://konyogony.dev/s/discord
    expectedStatusCodes:
      - 200
      - 308

  - name: "Redirect: Wakatime"
    url: https://konyogony.dev/s/wakatime
    expectedStatusCodes:
      - 200
      - 308

status-website:
  cname: status.konyogony.dev
  name: "@konyogony status"
